### **1. What is Docker, and how does it work?**

- **Answer**: Docker is a platform for developing, shipping, and running applications in isolated environments called _containers_. Containers package an application and its dependencies, ensuring it can run consistently on any environment. Docker uses a client-server architecture where:
  - The **Docker Client** is used to interact with Docker.
  - The **Docker Daemon** (Docker Engine) runs on the host machine and manages Docker objects like images, containers, networks, and volumes.
  - **Docker Images** are templates for creating containers.
  - **Containers** are running instances of Docker images.

### **2. What is the difference between a Docker image and a Docker container?**

- **Answer**:
  - A **Docker image** is a lightweight, stand-alone package containing everything needed to run a piece of software, including the code, runtime, libraries, and configuration files. It is static and immutable.
  - A **Docker container** is a running instance of a Docker image. It is dynamic, can have state, and can interact with other containers or the host system.

### **3. How do you create a Docker image?**

- **Answer**: You can create a Docker image using a **Dockerfile**, a text file that contains instructions to build the image. The steps typically include:
  - `FROM`: Specifies the base image.
  - `RUN`: Executes commands inside the container.
  - `COPY`/`ADD`: Adds files from the host to the image.
  - `CMD`/`ENTRYPOINT`: Defines the command that will run when the container starts.
- Build the image using:
  ```bash
  docker build -t <image_name> .
  ```

### **4. Explain the difference between CMD and ENTRYPOINT in a Dockerfile.**

- **Answer**:
  - **CMD** sets default commands or parameters that can be overridden when a container starts. It is generally used when you want to provide default arguments.
  - **ENTRYPOINT** sets the command that will always be executed when the container starts. It is used when you want your image to behave like an executable.
  - Example:
    ```dockerfile
    ENTRYPOINT ["python"]
    CMD ["app.py"]
    ```
    Running the container would execute `python app.py`.

### **5. How do you copy files from a container to the host and vice versa?**

- **Answer**:
  - Copy a file from the host to the container:
    ```bash
    docker cp <host_path> <container_id>:<container_path>
    ```
  - Copy a file from the container to the host:
    ```bash
    docker cp <container_id>:<container_path> <host_path>
    ```

### **6. What is Docker Compose, and how is it used?**

- **Answer**: **Docker Compose** is a tool for defining and running multi-container Docker applications using a YAML file (`docker-compose.yml`). It allows you to manage services, networks, and volumes in a single file. It is commonly used for defining multiple services that interact with each other, like a web server, a database, and a cache.
- Example `docker-compose.yml`:
  ```yaml
  version: "3"
  services:
    web:
      image: nginx
      ports:
        - "80:80"
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: example
  ```
  - To start the services, use: `docker-compose up`.

### **7. What is the purpose of Docker volumes, and how do they differ from bind mounts?**

- **Answer**:
  - **Docker volumes** are used for storing data generated by and used by Docker containers. They are managed by Docker, can be shared between containers, and persist even when containers are removed.
  - **Bind mounts** directly map a file or directory on the host system into a container, offering more control over host paths.
  - Use volumes when you don’t need to rely on host paths. Use bind mounts when you need access to a specific file or directory on the host.

### **8. How do you reduce the size of a Docker image?**

- **Answer**:
  - Use a **smaller base image**, like `alpine`.
  - **Combine multiple `RUN` statements** to reduce the number of layers.
  - **Clear package caches** after installations.
  - **Use multi-stage builds** to keep only the required files in the final image.

### **9. What are Docker namespaces and cgroups?**

- **Answer**:
  - **Namespaces** provide isolation for containers by segregating processes, networking, file systems, and more. Types include PID, Mount, Network, User, and IPC.
  - **cgroups** (control groups) limit the resources a process can use, such as CPU, memory, disk I/O, etc. This ensures that containers use only the resources they are allocated.

### **10. How does Docker networking work, and what are some types of Docker networks?**

- **Answer**: Docker networking allows containers to communicate with each other, the host system, and external networks. Types include:
  - **Bridge network**: Default network for standalone containers. Containers on the same bridge network can communicate.
  - **Host network**: Removes network isolation between the container and the Docker host.
  - **Overlay network**: Used for communication between containers across different Docker hosts in a swarm.
  - **None network**: Completely disables networking for a container.

### **11. How can you monitor Docker containers?**

- **Answer**: Docker provides various commands and tools for monitoring:
  - `docker stats`: Displays real-time stats for containers.
  - `docker logs <container_id>`: Shows logs of a container.
  - **Third-party tools** like Prometheus, Grafana, ELK stack, and Datadog can be used for more advanced monitoring.

### **12. What is the difference between Docker Swarm and Kubernetes?**

- **Answer**:
  - **Docker Swarm** is Docker's native clustering and orchestration tool, simpler to set up and use.
  - **Kubernetes** is a more powerful container orchestration tool with features like auto-scaling, self-healing, and complex networking. It has become the industry standard for orchestrating containers, but it has a steeper learning curve compared to Swarm.

### **13. What happens when you run `docker run -d`?**

- **Answer**: The `-d` flag stands for **detached mode**, which runs the container in the background. It returns the container ID, and the container keeps running without blocking the terminal.

### **14. How would you remove a Docker container and a Docker image?**

- **Answer**:
  - Remove a container:
    ```bash
    docker rm <container_id>
    ```
  - Remove a running container forcefully:
    ```bash
    docker rm -f <container_id>
    ```
  - Remove an image:
    ```bash
    docker rmi <image_id>
    ```

### **15. Explain the difference between `docker run` and `docker start`.**

- **Answer**:
  - `docker run` creates a new container from an image and starts it.
  - `docker start` starts an existing, stopped container.

Would you like more practice questions or need a deeper explanation on any of these?
